### ISSUE TITLE
DELETE repository

### ISSUE THREAD

**Issue by dginev** [KWARC/LaTeXML#12]
cc @kohlhase  @tkw1536 and @brucemiller 

Unsure if we should make a call to the community to see if someone is still using this fork, but now that all KWARC work is phased away from it, I would strongly recommend fully removing this github repository.

It also helps to avoid unneeded confusion that this fork is maintained/may be mantained in the future, which it isn't / won't be.

Let's see if this sounds good to everyone?

**Comment by tkw1536** [comment]
I think archiving it (i.e. making it read-only) is the better option.

**Comment by dginev** [comment]
To what merit? It's more likely that any use of this repository - old or new - is more harmful than beneficial.

**Comment by kohlhase** [comment]
I rather prefer archiving -- it seems wrong to throw away history --. For me it would be important that it disappears from the official LaTeXML forks list.

**Comment by tkw1536** [comment]
Since there were no further comments, I'll go ahead and archive this repository.
